import type { AppLanguage } from "@/types/setting";

export const chatEn = {
  yesterday: "Yesterday", workspace: "Workspace", loadingModels: "Loading models...", noModels: "No models available",
  currentModel: "Current model: {model}. Click to switch models", chatHistory: "Chat history", noChats: "No previous chats",
  permissionRequest: "Permission request", permissionQuestion: "Agent requests {operation} access to this path ({tool})",
  read: "read", write: "write", allowOnce: "Allow once", allowOnceDesc: "Allow only this tool operation",
  allowAlways: "Always allow", allowAlwaysDesc: "Do not ask again for this directory in this session", deny: "Deny", denyDesc: "Cancel this tool operation",
  customAnswer: "I'll type my answer", customAnswerDesc: "Skip these options and type an explanation below",
  aiResponding: "AI is responding...", openChatHint: "Use arrow keys and Enter to open a chat",
  permissionHint: "Use arrow keys and Enter to allow or deny", askHint: "Use arrow keys and Enter to confirm, or choose /custom to skip",
  askCustomHint: "Use arrow keys and Enter to confirm, or choose /custom to type an answer",
  yourChoice: "Your choice", thinking: "Thinking", thinkingProcess: "Thinking process", chars: "({count} characters)",
  executionDetails: "Execution details", fileOperations: "File operations", toolCount: "{count} tool(s)", fileCount: "({count} file(s))",
  processSummary: "Process details", thinkingCount: "{count} thinking step(s)",
  reading: "Reading", writing: "Writing", runningCommand: "Running command", working: "Working", responding: "Responding",
  waitingAnswer: "Waiting for answer...", waitingApproval: "Waiting for approval...", running: "Running...", failed: "Failed", edit: "Edit {count}", editContent: "Edit content", addContent: "Add content", deleteContent: "Delete content",
  select: "Select", send: "Send", pause: "Pause", chooseModel: "Choose model", loadingFiles: "Loading workspace files...", noMatchingFiles: "No matching files",
  continueQuestion: "Ask a follow-up...", askAnything: "Ask anything...", newChat: "New chat", expand: "Expand", close: "Close", collapse: "Collapse",
  showSecret: "Show secret", hideSecret: "Hide secret", userMessageNav: "User message navigation", jumpMessage: "Jump to message {count}",
  confirmSelection: "Confirm current selection", commandSuggestions: "Command suggestions", resetThemeColor: "Restore the theme default color",
  selectedFiles: "{file} and {count} more files", askSubmitFailed: "Failed to submit the answer: {error}. Please choose again.",
  toolApprovalTitle: "Tool approval", toolApprovalNoDiff: "No file preview for this tool.",
  toolApprovalMode: "Tool approval mode", currentApprovalMode: "Tool approval: {mode}. Click to switch",
  allowSession: "Allow this session", allowSessionDesc: "Remember this tool for the rest of the session",
  planModeActive: "Plan mode", planModeHint: "Writer tools are blocked until you approve the plan.",
  planModeApprove: "Approve & execute", planModeCancel: "Exit plan mode",
  rewind: "Undo", rewindCode: "Restore code", rewindConversation: "Restore conversation", rewindBoth: "Restore both",
  rewindConfirmTitle: "Confirm undo",
  rewindConfirm: "This will also restore code changes from this turn.",
  rewindConfirmAction: "Undo",
  rewindCancel: "Cancel",
  fuzzyMatch: "fuzzy",
} as const;

export type ChatI18nKey = keyof typeof chatEn;

export type LocalePartial = Partial<Record<ChatI18nKey, string>>;

export const chatLocales: Record<AppLanguage, LocalePartial> = {
  "en-US": chatEn,
  "zh-CN": { yesterday: "昨天", workspace: "工作区", loadingModels: "加载模型中...", noModels: "暂无可用模型", currentModel: "当前模型：{model}，点击切换模型", chatHistory: "历史对话", noChats: "暂无历史对话", permissionRequest: "权限申请", permissionQuestion: "Agent 请求{operation}该路径（{tool}）", read: "读取", write: "写入", allowOnce: "允许一次", allowOnceDesc: "仅允许本次工具操作", allowAlways: "始终允许", allowAlwaysDesc: "本会话内不再询问该目录", deny: "拒绝", denyDesc: "取消本次工具操作", customAnswer: "不选择，由我补充", customAnswerDesc: "不选择上述选项，在下方输入框补充说明", aiResponding: "AI 正在回复...", openChatHint: "方向键选择，Enter 打开会话", permissionHint: "方向键选择，Enter 确认是否允许访问", askHint: "方向键选择，Enter 确认；或选 /custom 跳过", askCustomHint: "方向键选择，Enter 确认；或选 /custom 由我补充说明", yourChoice: "你的选择", thinking: "思考", thinkingProcess: "思考过程", chars: "（{count} 字）", executionDetails: "执行过程", fileOperations: "操作过程", toolCount: "{count} 个工具", fileCount: "（{count} 个文件）", processSummary: "过程详情", thinkingCount: "{count} 段思考", reading: "读取中", writing: "编写中", runningCommand: "执行命令中", working: "执行中", responding: "回答中", waitingAnswer: "等待回答...", waitingApproval: "等待审批...", running: "执行中...", failed: "失败", edit: "修改 {count}", editContent: "修改内容", addContent: "新增内容", deleteContent: "删除内容", select: "请选择", send: "发送", pause: "暂停", chooseModel: "选择模型", loadingFiles: "正在读取工作区文件...", noMatchingFiles: "没有匹配的文件", continueQuestion: "继续提问...", askAnything: "随时提问...", newChat: "新对话", expand: "展开", close: "关闭", collapse: "折叠", showSecret: "显示密钥", hideSecret: "隐藏密钥", userMessageNav: "用户消息导航", jumpMessage: "跳转到第 {count} 条消息", toolApprovalTitle: "工具审批", toolApprovalNoDiff: "此工具没有文件预览。", toolApprovalMode: "工具审批模式", currentApprovalMode: "工具审批：{mode}，点击切换", allowSession: "本会话允许", allowSessionDesc: "本会话内记住该工具", planModeActive: "计划模式", planModeHint: "写操作已禁用，批准计划后开始执行。", planModeApprove: "批准并执行", planModeCancel: "退出计划", rewind: "撤回", rewindCode: "恢复代码", rewindConversation: "恢复对话", rewindBoth: "两者都恢复", rewindConfirmTitle: "确认撤回", rewindConfirm: "回退后，本回合修改的代码也会一并回退。", rewindConfirmAction: "撤回", rewindCancel: "取消", fuzzyMatch: "fuzzy" },
  "ja-JP": { yesterday: "昨日", workspace: "ワークスペース", loadingModels: "モデルを読み込み中...", noModels: "利用可能なモデルがありません", currentModel: "現在のモデル: {model}。クリックして切り替え", chatHistory: "チャット履歴", noChats: "チャット履歴がありません", permissionRequest: "権限のリクエスト", permissionQuestion: "Agent がこのパスへの{operation}アクセスを要求しています（{tool}）", read: "読み取り", write: "書き込み", allowOnce: "一度だけ許可", allowAlways: "常に許可", deny: "拒否", customAnswer: "自分で回答を入力", aiResponding: "AI が応答中...", yourChoice: "選択内容", thinking: "思考中", thinkingProcess: "思考過程", executionDetails: "実行の詳細", fileOperations: "ファイル操作", reading: "読み取り中", writing: "書き込み中", runningCommand: "コマンドを実行中", working: "作業中", responding: "応答中", waitingAnswer: "回答待ち...", running: "実行中...", failed: "失敗", select: "選択", send: "送信", pause: "一時停止", chooseModel: "モデルを選択", loadingFiles: "ワークスペースのファイルを読み込み中...", noMatchingFiles: "一致するファイルがありません", continueQuestion: "続けて質問...", askAnything: "何でも質問してください...", newChat: "新しいチャット", expand: "展開", close: "閉じる", collapse: "折りたたむ", showSecret: "シークレットを表示", hideSecret: "シークレットを非表示" },
  "ru-RU": { yesterday: "Вчера", workspace: "Рабочая область", loadingModels: "Загрузка моделей...", noModels: "Нет доступных моделей", currentModel: "Текущая модель: {model}. Нажмите, чтобы сменить", chatHistory: "История чатов", noChats: "История чатов пуста", permissionRequest: "Запрос разрешения", permissionQuestion: "Agent запрашивает доступ на {operation} к этому пути ({tool})", read: "чтение", write: "запись", allowOnce: "Разрешить один раз", allowAlways: "Разрешать всегда", deny: "Отклонить", customAnswer: "Я введу ответ", aiResponding: "ИИ отвечает...", yourChoice: "Ваш выбор", thinking: "Размышление", thinkingProcess: "Ход размышлений", executionDetails: "Ход выполнения", fileOperations: "Операции с файлами", reading: "Чтение", writing: "Запись", runningCommand: "Выполнение команды", working: "Выполнение", responding: "Формирование ответа", waitingAnswer: "Ожидание ответа...", running: "Выполняется...", failed: "Ошибка", select: "Выбрать", send: "Отправить", pause: "Пауза", chooseModel: "Выбрать модель", loadingFiles: "Загрузка файлов рабочей области...", noMatchingFiles: "Подходящих файлов нет", continueQuestion: "Задать следующий вопрос...", askAnything: "Спросите что-нибудь...", newChat: "Новый чат", expand: "Развернуть", close: "Закрыть", collapse: "Свернуть", showSecret: "Показать секрет", hideSecret: "Скрыть секрет" },
  "de-DE": { yesterday: "Gestern", workspace: "Arbeitsbereich", loadingModels: "Modelle werden geladen...", noModels: "Keine Modelle verfügbar", currentModel: "Aktuelles Modell: {model}. Zum Wechseln klicken", chatHistory: "Chatverlauf", noChats: "Keine früheren Chats", permissionRequest: "Berechtigungsanfrage", permissionQuestion: "Agent fordert {operation}-Zugriff auf diesen Pfad an ({tool})", read: "Lese", write: "Schreib", allowOnce: "Einmal erlauben", allowAlways: "Immer erlauben", deny: "Ablehnen", customAnswer: "Antwort selbst eingeben", aiResponding: "KI antwortet...", yourChoice: "Ihre Auswahl", thinking: "Denken", thinkingProcess: "Denkprozess", executionDetails: "Ausführungsdetails", fileOperations: "Dateioperationen", reading: "Wird gelesen", writing: "Wird geschrieben", runningCommand: "Befehl wird ausgeführt", working: "Wird ausgeführt", responding: "Antwort wird erstellt", waitingAnswer: "Warte auf Antwort...", running: "Wird ausgeführt...", failed: "Fehlgeschlagen", select: "Auswählen", send: "Senden", pause: "Pause", chooseModel: "Modell auswählen", loadingFiles: "Arbeitsbereichsdateien werden geladen...", noMatchingFiles: "Keine passenden Dateien", continueQuestion: "Weitere Frage...", askAnything: "Beliebige Frage stellen...", newChat: "Neuer Chat", expand: "Erweitern", close: "Schließen", collapse: "Einklappen", showSecret: "Geheimnis anzeigen", hideSecret: "Geheimnis ausblenden" },
  "fr-FR": { yesterday: "Hier", workspace: "Espace de travail", loadingModels: "Chargement des modèles...", noModels: "Aucun modèle disponible", currentModel: "Modèle actuel : {model}. Cliquez pour changer", chatHistory: "Historique des discussions", noChats: "Aucune discussion précédente", permissionRequest: "Demande d’autorisation", permissionQuestion: "Agent demande un accès en {operation} à ce chemin ({tool})", read: "lecture", write: "écriture", allowOnce: "Autoriser une fois", allowAlways: "Toujours autoriser", deny: "Refuser", customAnswer: "Je vais saisir ma réponse", aiResponding: "L’IA répond...", yourChoice: "Votre choix", thinking: "Réflexion", thinkingProcess: "Processus de réflexion", executionDetails: "Détails de l’exécution", fileOperations: "Opérations sur les fichiers", reading: "Lecture", writing: "Écriture", runningCommand: "Exécution de la commande", working: "Exécution", responding: "Rédaction de la réponse", waitingAnswer: "En attente d’une réponse...", running: "En cours...", failed: "Échec", select: "Sélectionner", send: "Envoyer", pause: "Pause", chooseModel: "Choisir un modèle", loadingFiles: "Chargement des fichiers de l’espace de travail...", noMatchingFiles: "Aucun fichier correspondant", continueQuestion: "Poser une autre question...", askAnything: "Posez une question...", newChat: "Nouvelle discussion", expand: "Développer", close: "Fermer", collapse: "Réduire", showSecret: "Afficher le secret", hideSecret: "Masquer le secret" },
  "ko-KR": { yesterday: "어제", workspace: "작업 영역", loadingModels: "모델 불러오는 중...", noModels: "사용 가능한 모델이 없습니다", currentModel: "현재 모델: {model}. 클릭하여 전환", chatHistory: "채팅 기록", noChats: "이전 채팅이 없습니다", permissionRequest: "권한 요청", permissionQuestion: "Agent가 이 경로에 대한 {operation} 권한을 요청합니다({tool})", read: "읽기", write: "쓰기", allowOnce: "한 번 허용", allowAlways: "항상 허용", deny: "거부", customAnswer: "직접 답변 입력", aiResponding: "AI 응답 중...", yourChoice: "선택 항목", thinking: "생각 중", thinkingProcess: "사고 과정", executionDetails: "실행 과정", fileOperations: "파일 작업", reading: "읽는 중", writing: "작성 중", runningCommand: "명령 실행 중", working: "작업 중", responding: "응답 중", waitingAnswer: "답변 대기 중...", running: "실행 중...", failed: "실패", select: "선택", send: "보내기", pause: "일시 정지", chooseModel: "모델 선택", loadingFiles: "작업 영역 파일을 불러오는 중...", noMatchingFiles: "일치하는 파일이 없습니다", continueQuestion: "추가 질문...", askAnything: "무엇이든 질문하세요...", newChat: "새 채팅", expand: "펼치기", close: "닫기", collapse: "접기", showSecret: "비밀 표시", hideSecret: "비밀 숨기기" },
};

export const chatSupplements: Partial<Record<AppLanguage, LocalePartial>> = {
  "zh-CN": { selectedFiles: "{file} 等 {count} 个文件", askSubmitFailed: "回答提交失败：{error}。请重新选择。" },
  "ja-JP": { allowOnceDesc: "このツール操作のみ許可します", allowAlwaysDesc: "このセッションではこのディレクトリを再確認しません", denyDesc: "このツール操作をキャンセルします", customAnswerDesc: "選択肢をスキップして下に回答を入力します", openChatHint: "矢印キーで選択し、Enter でチャットを開きます", permissionHint: "矢印キーで選択し、Enter で許可または拒否します", askHint: "矢印キーと Enter で確定するか、/custom でスキップします", askCustomHint: "矢印キーと Enter で確定するか、/custom で回答します", chars: "（{count} 文字）", toolCount: "ツール {count} 件", fileCount: "（ファイル {count} 件）", edit: "変更 {count}", editContent: "内容を変更", addContent: "内容を追加", deleteContent: "内容を削除", userMessageNav: "ユーザーメッセージナビゲーション", jumpMessage: "メッセージ {count} に移動", confirmSelection: "現在の選択を確定", commandSuggestions: "コマンド候補", resetThemeColor: "テーマの既定色に戻す" },
  "ru-RU": { allowOnceDesc: "Разрешить только эту операцию", allowAlwaysDesc: "Больше не спрашивать для этой папки в текущем сеансе", denyDesc: "Отменить эту операцию", customAnswerDesc: "Пропустить варианты и ввести пояснение ниже", openChatHint: "Выберите стрелками и нажмите Enter, чтобы открыть чат", permissionHint: "Выберите стрелками и нажмите Enter, чтобы разрешить или отклонить", askHint: "Выберите стрелками и Enter либо /custom для пропуска", askCustomHint: "Выберите стрелками и Enter либо /custom для своего ответа", chars: "({count} симв.)", toolCount: "Инструментов: {count}", fileCount: "(файлов: {count})", edit: "Изменение {count}", editContent: "Изменить содержимое", addContent: "Добавить содержимое", deleteContent: "Удалить содержимое", userMessageNav: "Навигация по сообщениям пользователя", jumpMessage: "Перейти к сообщению {count}", confirmSelection: "Подтвердить выбор", commandSuggestions: "Подсказки команд", resetThemeColor: "Восстановить цвет темы" },
  "de-DE": { allowOnceDesc: "Nur diesen Werkzeugvorgang erlauben", allowAlwaysDesc: "In dieser Sitzung für diesen Ordner nicht erneut fragen", denyDesc: "Diesen Werkzeugvorgang abbrechen", customAnswerDesc: "Optionen überspringen und unten eine Antwort eingeben", openChatHint: "Mit Pfeiltasten auswählen und mit Enter öffnen", permissionHint: "Mit Pfeiltasten auswählen und mit Enter erlauben oder ablehnen", askHint: "Mit Pfeiltasten und Enter bestätigen oder /custom zum Überspringen wählen", askCustomHint: "Mit Pfeiltasten und Enter bestätigen oder /custom für eine eigene Antwort wählen", chars: "({count} Zeichen)", toolCount: "{count} Werkzeuge", fileCount: "({count} Dateien)", edit: "Änderung {count}", editContent: "Inhalt ändern", addContent: "Inhalt hinzufügen", deleteContent: "Inhalt löschen", userMessageNav: "Navigation der Benutzernachrichten", jumpMessage: "Zu Nachricht {count} springen", confirmSelection: "Aktuelle Auswahl bestätigen", commandSuggestions: "Befehlsvorschläge", resetThemeColor: "Standardfarbe des Designs wiederherstellen" },
  "fr-FR": { allowOnceDesc: "Autoriser uniquement cette opération", allowAlwaysDesc: "Ne plus demander pour ce dossier pendant cette session", denyDesc: "Annuler cette opération", customAnswerDesc: "Ignorer les options et saisir une réponse ci-dessous", openChatHint: "Sélectionnez avec les flèches puis appuyez sur Entrée", permissionHint: "Sélectionnez avec les flèches puis appuyez sur Entrée pour autoriser ou refuser", askHint: "Confirmez avec les flèches et Entrée, ou choisissez /custom pour ignorer", askCustomHint: "Confirmez avec les flèches et Entrée, ou choisissez /custom pour répondre", chars: "({count} caractères)", toolCount: "{count} outils", fileCount: "({count} fichiers)", edit: "Modification {count}", editContent: "Modifier le contenu", addContent: "Ajouter du contenu", deleteContent: "Supprimer le contenu", userMessageNav: "Navigation des messages utilisateur", jumpMessage: "Aller au message {count}", confirmSelection: "Confirmer la sélection", commandSuggestions: "Suggestions de commandes", resetThemeColor: "Rétablir la couleur du thème" },
  "ko-KR": { allowOnceDesc: "이번 도구 작업만 허용합니다", allowAlwaysDesc: "이 세션에서 이 디렉터리를 다시 묻지 않습니다", denyDesc: "이번 도구 작업을 취소합니다", customAnswerDesc: "선택지를 건너뛰고 아래에 답변을 입력합니다", openChatHint: "방향키로 선택하고 Enter로 채팅을 엽니다", permissionHint: "방향키로 선택하고 Enter로 허용 또는 거부합니다", askHint: "방향키와 Enter로 확인하거나 /custom으로 건너뜁니다", askCustomHint: "방향키와 Enter로 확인하거나 /custom으로 직접 답변합니다", chars: "({count}자)", toolCount: "도구 {count}개", fileCount: "(파일 {count}개)", edit: "수정 {count}", editContent: "내용 수정", addContent: "내용 추가", deleteContent: "내용 삭제", userMessageNav: "사용자 메시지 탐색", jumpMessage: "{count}번째 메시지로 이동", confirmSelection: "현재 선택 확인", commandSuggestions: "명령 제안", resetThemeColor: "테마 기본 색상 복원" },
};
